#!/usr/bin/env node
/**
 * Parses the "Functional Parts List" section of Goodman's official GSXN4
 * repair parts manual (RP-G4328, © Goodman Manufacturing Company, L.P.,
 * September 2022) into a sourcedBatchLoader-compatible YAML batch.
 *
 * Input: plain text extracted via `pdftotext -layout <pdf> <txt>`.
 *
 * This document's own explicit "Expanded Model Nomenclature" section maps
 * M1-M7 to the exact 7 outdoor models already in the GSXN4 equipment-match
 * batch (GSXN401810AA through GSXN406010AA -- our data omits the trailing
 * "AA", handled below). Each parts row lists one part number, a
 * description, and which models it applies to in parens; no code at all
 * means the part applies to every model in the manual.
 *
 * Usage:
 *   node scripts/ingest/parseGoodmanGsxn4Parts.mjs <input.txt> <output.yaml>
 */
import fs from "node:fs";

const [, , inputPath, outputPath] = process.argv;
if (!inputPath || !outputPath) {
  console.error("Usage: parseGoodmanGsxn4Parts.mjs <input.txt> <output.yaml>");
  process.exit(1);
}

const SOURCE_URL = "https://hvacdirect.com/media/pdf/GSXN4%20Parts%20Manual.pdf";
const RETRIEVED_AT = "2026-08-16";

// From the document's own "Expanded Model Nomenclature" -- our equipment
// data uses these models without the trailing "AA" suffix this manual uses.
const MODEL_CODES = {
  M1: "GSXN401810",
  M2: "GSXN402410",
  M3: "GSXN403010",
  M4: "GSXN403610",
  M5: "GSXN404210",
  M6: "GSXN404810",
  M7: "GSXN406010",
};
const ALL_MODELS = Object.values(MODEL_CODES);

const CATEGORY_KEYWORDS = [
  ["capacitor", /\bCAP\b|CAPACITOR/i],
  ["compressor", /COMPRESSOR/i],
  ["contactor", /CONTACTOR/i],
  ["motor", /\bMOTOR\b/i],
  ["fan blade", /BLADE|FAN BLADE/i],
  ["valve", /VALVE/i],
  ["relay", /RELAY/i],
  ["switch", /\bSW-|SWITCH/i],
  ["thermostat", /THERMOSTAT/i],
  ["heater", /HEATER/i],
];
function categorize(description) {
  for (const [category, pattern] of CATEGORY_KEYWORDS) {
    if (pattern.test(description)) return category;
  }
  return null;
}

const rawText = fs.readFileSync(inputPath, "utf-8");
const startMarker = /Part\s*\n\s*No:\s*Description:/;
const startMatch = rawText.match(startMarker);
const endIndex = rawText.indexOf("SPECIAL PARTS");
if (!startMatch || endIndex === -1) {
  console.error("Could not find the Functional Parts List section boundaries -- document format may have changed.");
  process.exit(1);
}
const section = rawText.slice(startMatch.index + startMatch[0].length, endIndex);

// Merge wrapped lines: a continuation line is whitespace-only content
// ending the model-code parenthetical on its own line, e.g. a row split as
// "...(M5, M6,\n    M7)".
const lines = section.split("\n").map((l) => l.trimEnd());
const merged = [];
for (const line of lines) {
  if (!line.trim()) continue;
  const isContinuation = /^\s*M\d+\)\s*$/.test(line) && merged.length > 0;
  if (isContinuation) {
    merged[merged.length - 1] += " " + line.trim();
  } else {
    merged.push(line);
  }
}

const records = [];
const rowPattern = /^(\S+)\s{2,}(.+?)(?:\s*\(([^)]+)\))?\s*$/;
for (const line of merged) {
  const m = line.match(rowPattern);
  if (!m) {
    console.warn(`Skipped unparseable line: "${line}"`);
    continue;
  }
  const [, partNumber, description, modelCodesRaw] = m;
  const models = modelCodesRaw
    ? modelCodesRaw.split(",").map((c) => MODEL_CODES[c.trim()]).filter(Boolean)
    : ALL_MODELS;

  if (modelCodesRaw && models.length === 0) {
    console.warn(`Line had a parenthetical that didn't resolve to any known model code: "${line}"`);
    continue;
  }

  for (const model of models) {
    records.push({
      outdoor_model: model,
      part_number: partNumber,
      description: description.trim(),
      category: categorize(description),
    });
  }
}

console.log(`Parsed ${records.length} (model, part) pairs from ${new Set(records.map((r) => r.part_number)).size} distinct parts.`);

const yamlLines = [];
yamlLines.push(
  "# Ingestion batch: Goodman GSXN4 official repair parts manual (RP-G4328,",
  "# © Goodman Manufacturing Company, L.P., September 2022), Functional Parts",
  "# List section only (illustration/diagram sections not parsed in this pass).",
  "#",
  "# Generated by scripts/ingest/parseGoodmanGsxn4Parts.mjs -- do not hand-edit;",
  "# re-run the script against a fresh copy of the PDF and commit the",
  "# regenerated output instead.",
  "#",
  "# confidence: verified -- this is Goodman's own official parts manual",
  "# (copyright notice in the document itself), not a third-party listing.",
  "# 'category' is a keyword-derived UI grouping label for filtering, not a",
  "# manufacturer-stated fact -- flagged as such, not presented as sourced data.",
  "document:",
  `  source_url: "${SOURCE_URL}"`,
  "  source_type: manufacturer_pdf",
  `  retrieved_at: ${RETRIEVED_AT}`,
  "  brand: Goodman",
  "  confidence: verified",
  "",
  "records:",
);

for (const r of records) {
  yamlLines.push(`  - outdoor_model: ${JSON.stringify(r.outdoor_model)}`);
  yamlLines.push(`    part_number: ${JSON.stringify(r.part_number)}`);
  yamlLines.push(`    description: ${JSON.stringify(r.description)}`);
  if (r.category) yamlLines.push(`    category: ${JSON.stringify(r.category)}`);
  yamlLines.push("");
}

fs.writeFileSync(outputPath, yamlLines.join("\n"));
console.log(`Wrote ${records.length} records to ${outputPath}`);
